sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t baha/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true baha/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-263139023809"
  on:
    branch: master

  access_key_id:
    secure: $aws-access-key 
  secret_access_key:
    secure: $aws-secret-key
