sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t baha/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true baha/docker-react npm run test